export const retailers = [
  {
    id: "sklavenitis",
    name: "Σκλαβενίτης",
    shortName: "ΣΚ",
    color: "#0f766e",
  },
  {
    id: "ab_vasilopoulos",
    name: "ΑΒ Βασιλόπουλος",
    shortName: "ΑΒ",
    color: "#2563eb",
  },
  {
    id: "lidl",
    name: "Lidl",
    shortName: "LD",
    color: "#f59e0b",
  },
  {
    id: "mymarket",
    name: "My market",
    shortName: "MY",
    color: "#ef4444",
  },
  {
    id: "masoutis",
    name: "Μασούτης",
    shortName: "ΜΣ",
    color: "#16a34a",
  },
  {
    id: "kritikos",
    name: "Κρητικός",
    shortName: "ΚΡ",
    color: "#7c3aed",
  },
];

export const products = [
  {
    id: "milk-1l",
    gtin: "5201054020902",
    name: "Γάλα φρέσκο πλήρες 1L",
    brand: "Δέλτα",
    category: "Γαλακτοκομικά",
    unit: "τεμ.",
    unitQuantity: "1 L",
    tile: "γά",
    tint: "#dbeafe",
    description: "Φρέσκο πλήρες γάλα ψυγείου για καθημερινό καλάθι.",
    prices: {
      sklavenitis: 1.74,
      ab_vasilopoulos: 1.82,
      lidl: 1.57,
      mymarket: 1.79,
      masoutis: 1.69,
      kritikos: 1.85,
    },
  },
  {
    id: "yogurt-strained",
    gtin: "5201059001159",
    name: "Γιαούρτι στραγγιστό 2% 1kg",
    brand: "Όλυμπος",
    category: "Γαλακτοκομικά",
    unit: "τεμ.",
    unitQuantity: "1 kg",
    tile: "για",
    tint: "#e0f2fe",
    description: "Στραγγιστό γιαούρτι μεσαίας λιπαρότητας.",
    prices: {
      sklavenitis: 4.18,
      ab_vasilopoulos: 4.42,
      lidl: 3.79,
      mymarket: 4.09,
      masoutis: 4.22,
      kritikos: 4.35,
    },
  },
  {
    id: "coffee-greek",
    gtin: "5201005002114",
    name: "Ελληνικός καφές 194g",
    brand: "Λουμίδης",
    category: "Καφές",
    unit: "τεμ.",
    unitQuantity: "194 g",
    tile: "κα",
    tint: "#fee2e2",
    description: "Κλασικός ελληνικός καφές, αλεσμένος.",
    prices: {
      sklavenitis: 3.12,
      ab_vasilopoulos: 3.35,
      lidl: null,
      mymarket: 3.18,
      masoutis: 3.09,
      kritikos: 3.28,
    },
  },
  {
    id: "pasta-spaghetti",
    gtin: "5201013001024",
    name: "Σπαγγέτι Νο6 500g",
    brand: "Μέλισσα",
    category: "Ζυμαρικά",
    unit: "τεμ.",
    unitQuantity: "500 g",
    tile: "ζυ",
    tint: "#fef3c7",
    description: "Κλασικά ζυμαρικά για βασικό εβδομαδιαίο καλάθι.",
    prices: {
      sklavenitis: 1.08,
      ab_vasilopoulos: 1.18,
      lidl: 0.89,
      mymarket: 1.05,
      masoutis: 1.12,
      kritikos: 1.2,
    },
  },
  {
    id: "rice-carolina",
    gtin: "5201001008516",
    name: "Ρύζι Καρολίνα 500g",
    brand: "Agrino",
    category: "Ρύζι",
    unit: "τεμ.",
    unitQuantity: "500 g",
    tile: "ρύ",
    tint: "#dcfce7",
    description: "Ρύζι για μαγείρεμα και σούπες.",
    prices: {
      sklavenitis: 1.72,
      ab_vasilopoulos: 1.88,
      lidl: 1.55,
      mymarket: 1.69,
      masoutis: 1.79,
      kritikos: null,
    },
  },
  {
    id: "olive-oil",
    gtin: "5201046029012",
    name: "Εξαιρετικό παρθένο ελαιόλαδο 1L",
    brand: "Άλτις",
    category: "Έλαια",
    unit: "τεμ.",
    unitQuantity: "1 L",
    tile: "ελ",
    tint: "#fef9c3",
    description: "Ελαιόλαδο πρώτης πίεσης για γενική χρήση.",
    prices: {
      sklavenitis: 10.95,
      ab_vasilopoulos: 11.48,
      lidl: 10.39,
      mymarket: 10.89,
      masoutis: 11.15,
      kritikos: 11.59,
    },
  },
  {
    id: "water-sixpack",
    gtin: "5201018000084",
    name: "Νερό φυσικό 6x1.5L",
    brand: "Ζαγόρι",
    category: "Νερά",
    unit: "συσκ.",
    unitQuantity: "9 L",
    tile: "νε",
    tint: "#cffafe",
    description: "Εξάδα εμφιαλωμένου νερού.",
    prices: {
      sklavenitis: 2.04,
      ab_vasilopoulos: 2.18,
      lidl: 1.86,
      mymarket: 2.0,
      masoutis: 2.08,
      kritikos: 2.2,
    },
  },
  {
    id: "detergent",
    gtin: "8710447361543",
    name: "Απορρυπαντικό πλυντηρίου 40 μεζ.",
    brand: "Skip",
    category: "Καθαριστικά",
    unit: "τεμ.",
    unitQuantity: "40 μεζ.",
    tile: "σκ",
    tint: "#e0e7ff",
    description: "Σκόνη/υγρό απορρυπαντικό γενικής χρήσης.",
    prices: {
      sklavenitis: 11.75,
      ab_vasilopoulos: 12.4,
      lidl: null,
      mymarket: 10.95,
      masoutis: 11.89,
      kritikos: 12.15,
    },
  },
  {
    id: "toilet-paper",
    gtin: "5201263005312",
    name: "Χαρτί υγείας 10 ρολά",
    brand: "Softex",
    category: "Χαρτικά",
    unit: "συσκ.",
    unitQuantity: "10 ρολά",
    tile: "χα",
    tint: "#f5f3ff",
    description: "Οικιακή συσκευασία χαρτιού υγείας.",
    prices: {
      sklavenitis: 5.48,
      ab_vasilopoulos: 5.72,
      lidl: 4.79,
      mymarket: 5.18,
      masoutis: 5.39,
      kritikos: 5.68,
    },
  },
  {
    id: "cereal",
    gtin: "7613035132261",
    name: "Δημητριακά ολικής 375g",
    brand: "Fitness",
    category: "Πρωινό",
    unit: "τεμ.",
    unitQuantity: "375 g",
    tile: "δη",
    tint: "#ffedd5",
    description: "Δημητριακά πρωινού ολικής άλεσης.",
    prices: {
      sklavenitis: 3.88,
      ab_vasilopoulos: 4.05,
      lidl: null,
      mymarket: 3.79,
      masoutis: 3.92,
      kritikos: 4.1,
    },
  },
  {
    id: "eggs",
    gtin: "5201302000107",
    name: "Αυγά μεσαία 6 τεμ.",
    brand: "Χρυσά Αυγά",
    category: "Ψυγείο",
    unit: "συσκ.",
    unitQuantity: "6 τεμ.",
    tile: "αυ",
    tint: "#fef2f2",
    description: "Μεσαία αυγά σε εξάδα.",
    prices: {
      sklavenitis: 2.78,
      ab_vasilopoulos: 2.95,
      lidl: 2.49,
      mymarket: null,
      masoutis: 2.84,
      kritikos: 2.98,
    },
  },
  {
    id: "tomatoes",
    gtin: "produce-tomatoes",
    name: "Ντομάτες χύμα",
    brand: "Μαναβική",
    category: "Μαναβική",
    unit: "kg",
    unitQuantity: "1 kg",
    tile: "ντ",
    tint: "#fee2e2",
    description: "Ενδεικτική τιμή ανά κιλό για μαναβική.",
    prices: {
      sklavenitis: 1.98,
      ab_vasilopoulos: 2.2,
      lidl: 1.69,
      mymarket: 1.89,
      masoutis: 2.05,
      kritikos: 1.92,
    },
  },
];

export const initialBasket = [
  { productId: "milk-1l", quantity: 2 },
  { productId: "coffee-greek", quantity: 1 },
  { productId: "pasta-spaghetti", quantity: 3 },
  { productId: "yogurt-strained", quantity: 1 },
  { productId: "tomatoes", quantity: 1.5 },
];
